name: Run Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
        playwright install 

    - name: Run Playwright tests with Allure results
      run: |
        pytest test.py --alluredir=allure-results

    - name: Download Allure
      run: |
        curl -o allure-commandline.zip -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
        unzip allure-commandline.zip -d /opt/allure
        export PATH=$PATH:/opt/allure/allure-2.21.0/bin

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

#    - name: Run Python script
#      run: |
#        python test.py
