name: Run Python Code with allure and gh pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
        pip install allure-pytest
        playwright install 

    - name: Run Playwright tests with Allure results
      run: |
        pytest tests.py --alluredir=allure-results

    - name: Download Allure
      run: |
        curl -o allure-commandline.zip -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
        unzip allure-commandline.zip -d /opt/allure
        export PATH=$PATH:/opt/allure/allure-2.21.0/bin
        sudo ln -s /opt/allure/allure-2.21.0/bin/allure /usr/bin/allure

    - name: Verify Allure Installation
      run: |
        allure --version

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add allure-report
        git commit -m "Deploy Allure Report to GitHub Pages"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" `gh-pages`

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report